-- Generated by Oracle SQL Developer Data Modeler 19.1.0.081.0911
--   at:        2019-11-21 22:57:31 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

DROP TABLE IF EXISTS hist_dolad;
DROP TABLE IF EXISTS pracownicy;
DROP TABLE IF EXISTS poz_cennik;
DROP TABLE IF EXISTS slownik_cennik;
DROP TABLE IF EXISTS cennik;
DROP TABLE IF EXISTS uzycia_karnetu;
DROP TABLE IF EXISTS karnet;
DROP TABLE IF EXISTS wyciag_dane;
DROP TABLE IF EXISTS zarzadcy;
DROP TABLE IF EXISTS kierownik;
DROP TABLE IF EXISTS wyciag;

ALTER DATABASE slavek_bd2 CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE cennik (
    id   				INTEGER PRIMARY KEY AUTO_INCREMENT,
    od   				DATETIME,
    kierownik_id   	INTEGER NOT NULL,
    odw_przed_wej		BOOLEAN DEFAULT FALSE
)
CHARACTER SET=utf8;

CREATE TABLE hist_dolad (
	 id 					INTEGER PRIMARY KEY AUTO_INCREMENT,
    l_pkt            INTEGER,
    stempelczasowy   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    karnet_id        INTEGER NOT NULL,
    pracownicy_id    INTEGER NOT NULL,
    poz_cennik_id    INTEGER NOT NULL
)
CHARACTER SET=utf8;

CREATE TABLE karnet (
    id INTEGER  PRIMARY KEY AUTO_INCREMENT,
    zablokowany BOOLEAN DEFAULT FALSE
)
CHARACTER SET=utf8;

CREATE TABLE kierownik (
    id         INTEGER PRIMARY KEY AUTO_INCREMENT,
    nazwisko   VARCHAR(50),
    imie       VARCHAR(50),
    login      VARCHAR(50),
    haslo      VARCHAR(50),
    zwolniony  BOOLEAN DEFAULT FALSE
)
CHARACTER SET=utf8;

CREATE TABLE poz_cennik (
    id                  INTEGER PRIMARY KEY AUTO_INCREMENT,
    cena                DOUBLE NOT NULL,
    cennik_id           INTEGER NOT NULL,
    slownik_cennik_id   INTEGER NOT NULL
)
CHARACTER SET=utf8;

CREATE TABLE pracownicy (
    id             INTEGER PRIMARY KEY AUTO_INCREMENT,
    nazwisko       VARCHAR(50),
    imie           VARCHAR(50),
    login          VARCHAR(50),
    haslo          VARCHAR(50),
    kierownik_id   INTEGER NOT NULL,
    zwolniony      BOOLEAN DEFAULT FALSE
)
CHARACTER SET=utf8;

CREATE TABLE slownik_cennik (
    id      INTEGER PRIMARY KEY AUTO_INCREMENT,
    nazwa   VARCHAR(50)
)
CHARACTER SET=utf8;

CREATE TABLE uzycia_karnetu (
    id               INTEGER PRIMARY KEY AUTO_INCREMENT,
    stempelczasowy   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    wyciag_dane_id   INTEGER NOT NULL,
    karnet_id        INTEGER NOT NULL
)
CHARACTER SET=utf8;

CREATE TABLE wyciag (
    id              INTEGER PRIMARY KEY AUTO_INCREMENT,
    nazwa           VARCHAR(50),
    wysokosc        DOUBLE
)
CHARACTER SET=utf8;

CREATE TABLE wyciag_dane (
    id              INTEGER PRIMARY KEY AUTO_INCREMENT,
    od              DATETIME,
    koszt_pkt       INTEGER,
	 stan            BOOLEAN DEFAULT FALSE,
    nieistniejacy   BOOLEAN DEFAULT FALSE,
    wyciag_id       INTEGER NOT NULL,
    kierownik_id    INTEGER NOT NULL
)
CHARACTER SET=utf8;

CREATE TABLE zarzadcy (
    id               INTEGER PRIMARY KEY AUTO_INCREMENT,
    od               DATETIME,
    do               DATETIME,
    kierownik_id     INTEGER NOT NULL,
    wyciag_id        INTEGER NOT NULL
)
CHARACTER SET=utf8;

ALTER TABLE cennik
    ADD CONSTRAINT cennik_kierownik_fk FOREIGN KEY ( kierownik_id )
        REFERENCES kierownik ( id );

ALTER TABLE hist_dolad
    ADD CONSTRAINT hist_dolad_karnet_fk FOREIGN KEY ( karnet_id )
        REFERENCES karnet ( id );

ALTER TABLE hist_dolad
    ADD CONSTRAINT hist_dolad_poz_cennik_fk FOREIGN KEY ( poz_cennik_id )
        REFERENCES poz_cennik ( id );

ALTER TABLE hist_dolad
    ADD CONSTRAINT hist_dolad_pracownicy_fk FOREIGN KEY ( pracownicy_id )
        REFERENCES pracownicy ( id );

ALTER TABLE poz_cennik
    ADD CONSTRAINT poz_cennik_cennik_fk FOREIGN KEY ( cennik_id )
        REFERENCES cennik ( id );

ALTER TABLE poz_cennik
    ADD CONSTRAINT poz_cennik_slownik_cennik_fk FOREIGN KEY ( slownik_cennik_id )
        REFERENCES slownik_cennik ( id );

ALTER TABLE pracownicy
    ADD CONSTRAINT pracownicy_kierownik_fk FOREIGN KEY ( kierownik_id )
        REFERENCES kierownik ( id );

ALTER TABLE uzycia_karnetu
    ADD CONSTRAINT uzycia_karnetu_karnet_fk FOREIGN KEY ( karnet_id )
        REFERENCES karnet ( id );

ALTER TABLE uzycia_karnetu
    ADD CONSTRAINT uzycia_karnetu_wyciag_dane_fk FOREIGN KEY ( wyciag_dane_id )
        REFERENCES wyciag_dane ( id );

ALTER TABLE wyciag_dane
    ADD CONSTRAINT wyciag_dane_kierownik_fk FOREIGN KEY ( kierownik_id )
        REFERENCES kierownik ( id );

ALTER TABLE wyciag_dane
    ADD CONSTRAINT wyciag_dane_wyciag_fk FOREIGN KEY ( wyciag_id )
        REFERENCES wyciag ( id );

ALTER TABLE zarzadcy
    ADD CONSTRAINT zarzadcy_kierownik_fk FOREIGN KEY ( kierownik_id )
        REFERENCES kierownik ( id );

ALTER TABLE zarzadcy
    ADD CONSTRAINT zarzadcy_wyciag_fk FOREIGN KEY ( wyciag_id )
        REFERENCES wyciag ( id );


--INSERT INTO karnet values (null);

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
